/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w5kCuEGNzcTGjsZgQWxRDG

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsuptH9QiIo64W } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: uptH9QiIO64w/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsuptH9QiIo64W
});
